### ISSUE TITLE
Question on Adding Images

### ISSUE THREAD

**Issue by bikathi** [modbender/nuxt-tiptap-editor#1]
Hey, thanks for this awesome Nuxt plugin. I am customizing it for use in my own project but I am having issues figuring out how to add images. The official TipTap has VueJS documentation here [TipTap working with images](https://tiptap.dev/docs/editor/api/nodes/image) but I can seem to get it to properly work.
Any leads or code samples on how I can do this?

**Comment by modbender** [comment]
Hey sorry for the late answer

The documentation is actually incomplete about this right now, so let me first tell you that out of the box not all extensions are installed together with this plugin, because there are many external plugins that needs manual installation given by TipTap themselves.

By default all the extensions that come with [StarterKit](https://tiptap.dev/docs/editor/api/extensions/starter-kit) is installed and any other except the one mentioned in [Extension](https://github.com/modbender/nuxt-tiptap-editor?tab=readme-ov-file#extension) section of README needs to be installed manually. Because if all of them are included then node_modules would end up taking space regardless of whether you use those extensions or not.

Atleast this is the case for now, which might change in future.

You can view in [defaults.ts](https://github.com/modbender/nuxt-tiptap-editor/blob/main/src/imports/defaults.ts) for list of available extensions without manual installation

For the `Image` that you are asking for you need to do something like below in your vue file:


```xml
<script setup>
import Image from "@tiptap/extension-image";

const editor = useEditor({
  autofocus: false,
  extensions: [
    TiptapStarterKit.configure({
      codeBlock: false,
    }),
    Image,
  ],
});
```

P.S you might need [FileHandler](https://tiptap.dev/docs/editor/api/extensions/file-handler) if you are planning for uploading images.

**Comment by bikathi** [comment]
Hey @modbender. Sorry it took time to come back with a response. Your works 100% fine. I am able to add an image by hard-coding a URL into the  `.setImage()` function like this:
```
.setImage({
	src: 'https://images.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg',
	alt: 'Sample Alt Text',
})
```
However, the FileHandler seems to be paid so it's not an option for me. That's not an issue though. A simple workaround is to change the button that inserts the file into an `<input type="file" />` then add some event listener to upload the select file to a custom endpoint and get back the link then I can call the `setImage()` with that link. Thank you so much for your help.

**Comment by modbender** [comment]
Ok glad it helped!
